version: '3'
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    volumes:
      - /mongoData:/data/db
    ports:
      - 27017:27017
    networks:
      - production-network

  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: myapp
    container_name: "bovControl-api"
    ports:
      - 3000:3000
    networks:
      - production-network
    depends_on:
      - "mongodb"

networks:
  production-network:
    driver: bridge